import type { MarkerCategories } from '../../../types';

const mapZoomLevelToOutlineThickness: Record<
  number,
  Record<MarkerCategories, number>
> = {
  1: {
    custom: 0,
    dragons: 0,
    portals: 0.8,
    quests: 0,
    chests: 0.2,
    bountyHunt: 0.5,
    regionBoss: 0,
    caves: 0.2,
  },
  4: {
    custom: 0,
    dragons: 0,
    portals: 0.8,
    quests: 0,
    chests: 0.5,
    bountyHunt: 0.8,
    regionBoss: 0,
    caves: 0.5,
  },
  6: {
    custom: 0,
    dragons: 0,
    portals: 0.8,
    quests: 0,
    chests: 0.5,
    bountyHunt: 0.8,
    regionBoss: 0,
    caves: 0.5,
  },
  8: {
    custom: 0,
    dragons: 0.2,
    portals: 1.4,
    quests: 0.2,
    chests: 1.1,
    bountyHunt: 1,
    regionBoss: 0.2,
    caves: 0.8,
  },
  9: {
    custom: 0,
    dragons: 0.2,
    portals: 1.4,
    quests: 0.2,
    chests: 1.1,
    bountyHunt: 1,
    regionBoss: 0.2,
    caves: 0.8,
  },
  10: {
    custom: 0,
    dragons: 0.2,
    portals: 1.4,
    quests: 0.2,
    chests: 1.1,
    bountyHunt: 1.2,
    regionBoss: 0.2,
    caves: 0.8,
  },
  11: {
    custom: 0,
    dragons: 0.4,
    portals: 1.8,
    quests: 0.4,
    chests: 1.4,
    bountyHunt: 1.6,
    regionBoss: 0.4,
    caves: 1.3,
  },
  12: {
    custom: 0,
    dragons: 1,
    portals: 2,
    quests: 1.2,
    chests: 1.9,
    bountyHunt: 2,
    regionBoss: 0.7,
    caves: 1.8,
  },
};

export default mapZoomLevelToOutlineThickness;
